-- VoleyDB — esquema (MySQL 8). Convenciones Academia / Kaysen:
-- tablas y columnas en MAYUSCULAS, fechas CHAR(8) DDMMYYYY, modelos Django managed=False.

DROP DATABASE IF EXISTS `VoleyDB`;
CREATE DATABASE `VoleyDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `VoleyDB`;

CREATE TABLE TIPOUSUARIO (
    IDTIPOUSUARIO VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPCION   VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE USUARIO (
    IDUSUARIO     VARCHAR(50)  NOT NULL PRIMARY KEY,
    CONTRA        VARCHAR(255) NOT NULL,
    NOMBRE        VARCHAR(100) NOT NULL,
    APELLIDO      VARCHAR(100) NOT NULL,
    DNI           VARCHAR(20)  NOT NULL,
    EMAIL         VARCHAR(150) NULL,
    ESTADO        VARCHAR(50)  NOT NULL DEFAULT 'Activo',
    IDTIPOUSUARIO VARCHAR(50)  NOT NULL,
    CONSTRAINT FK_USUARIO_TIPO FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO)
) ENGINE=InnoDB;

CREATE TABLE MODULO (
    IDMODULO    VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE      VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ICONO       VARCHAR(100) NULL,
    ORDEN       INT NULL,
    ACTIVO      TINYINT(1) NOT NULL DEFAULT 1,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE SUBMODULO (
    IDSUBMODULO VARCHAR(50)  NOT NULL PRIMARY KEY,
    NOMBRE      VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ICONO       VARCHAR(100) NULL,
    ORDEN       INT NULL,
    ACTIVO      TINYINT(1) NOT NULL DEFAULT 1,
    IDMODULO    VARCHAR(50) NOT NULL,
    CONSTRAINT FK_SUB_MODULO FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO)
) ENGINE=InnoDB;

CREATE TABLE TIPO_PERMISO (
    IDTIPOPERMISO VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPCION   VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GRUPO_MODULO (
    IDGRUPOMODULO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO VARCHAR(50) NOT NULL,
    IDMODULO      VARCHAR(50) NOT NULL,
    IDTIPOPERMISO VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_GRUPO_MODULO UNIQUE (IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO),
    CONSTRAINT FK_GM_TIPO FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    CONSTRAINT FK_GM_MOD FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    CONSTRAINT FK_GM_PERM FOREIGN KEY (IDTIPOPERMISO) REFERENCES TIPO_PERMISO(IDTIPOPERMISO)
) ENGINE=InnoDB;

CREATE TABLE USUARIO_MODULO (
    IDUSUARIOMODULO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO       VARCHAR(50) NOT NULL,
    IDMODULO        VARCHAR(50) NOT NULL,
    IDTIPOPERMISO   VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_USUARIO_MODULO UNIQUE (IDUSUARIO, IDMODULO, IDTIPOPERMISO),
    CONSTRAINT FK_UM_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_UM_MOD FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    CONSTRAINT FK_UM_PERM FOREIGN KEY (IDTIPOPERMISO) REFERENCES TIPO_PERMISO(IDTIPOPERMISO)
) ENGINE=InnoDB;

CREATE TABLE USUARIO_MODULO_EXCLUIDO (
    IDUSUARIOEXCLUIDO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO VARCHAR(50) NOT NULL,
    IDMODULO  VARCHAR(50) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    CONSTRAINT UQ_UME UNIQUE (IDUSUARIO, IDMODULO),
    CONSTRAINT FK_UME_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_UME_MOD FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO)
) ENGINE=InnoDB;

CREATE TABLE USUARIO_SUBMODULO_EXCLUIDO (
    IDUSUARIOEXCLSUB VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO   VARCHAR(50) NOT NULL,
    IDSUBMODULO VARCHAR(50) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    CONSTRAINT UQ_USE UNIQUE (IDUSUARIO, IDSUBMODULO),
    CONSTRAINT FK_USE_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_USE_SUB FOREIGN KEY (IDSUBMODULO) REFERENCES SUBMODULO(IDSUBMODULO)
) ENGINE=InnoDB;

CREATE TABLE USUARIO_SUBMODULO_INCLUIDO (
    IDUSUARIOINCLSUB VARCHAR(50) NOT NULL PRIMARY KEY,
    IDUSUARIO   VARCHAR(50) NOT NULL,
    IDSUBMODULO VARCHAR(50) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    CONSTRAINT UQ_USI UNIQUE (IDUSUARIO, IDSUBMODULO),
    CONSTRAINT FK_USI_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_USI_SUB FOREIGN KEY (IDSUBMODULO) REFERENCES SUBMODULO(IDSUBMODULO)
) ENGINE=InnoDB;

CREATE TABLE GRUPO_SUBMODULO_EXCLUIDO (
    IDGRUPOEXCLSUB VARCHAR(50) NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO VARCHAR(50) NOT NULL,
    IDSUBMODULO   VARCHAR(50) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    CONSTRAINT UQ_GSE UNIQUE (IDTIPOUSUARIO, IDSUBMODULO),
    CONSTRAINT FK_GSE_TIPO FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    CONSTRAINT FK_GSE_SUB FOREIGN KEY (IDSUBMODULO) REFERENCES SUBMODULO(IDSUBMODULO)
) ENGINE=InnoDB;

CREATE TABLE CICLO (
    IDCICLO VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE  VARCHAR(120) NOT NULL,
    SLUG    VARCHAR(60) NULL,
    ACTIVO  TINYINT(1) NOT NULL DEFAULT 1,
    ORDEN   INT NOT NULL DEFAULT 0,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE TURNO (
    IDTURNO VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    HORAINICIO CHAR(5) NOT NULL,
    HORAFIN CHAR(5) NOT NULL,
    DIASACTIVOS VARCHAR(120) NULL,
    ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE ALUMNA (
    IDALUMNA VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    EDAD SMALLINT NULL,
    DNI VARCHAR(15) NULL,
    EMAIL VARCHAR(150) NULL,
    TELEFONO VARCHAR(200) NULL,
    GENERO VARCHAR(20) NULL,
    IDCICLO VARCHAR(50) NULL,
    CONDICION VARCHAR(30) NOT NULL DEFAULT 'Regular',
    COLEGIO VARCHAR(120) NULL,
    TALLA VARCHAR(5) NULL,
    SUFREDE VARCHAR(255) NULL,
    COMOENTERO VARCHAR(200) NULL,
    UNIFORMEENTREGADO TINYINT(1) NOT NULL DEFAULT 0,
    APODERADO VARCHAR(120) NULL,
    DNIAPODERADO VARCHAR(15) NULL,
    FECHANACAPODERADO CHAR(8) NULL,
    GENEROAPODERADO VARCHAR(20) NULL,
    TELAPODERADO VARCHAR(200) NULL,
    DIRECCION VARCHAR(500) NULL,
    IDTURNO VARCHAR(50) NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'Activa',
    MOTIVORETIRO VARCHAR(500) NULL,
    FECHARETIRO CHAR(8) NULL,
    MENSUALIDAD DECIMAL(10,2) NULL,
    FECHAINSCRIPCION CHAR(8) NULL,
    INICIOMENSUALIDAD CHAR(8) NULL,
    FINMENSUALIDAD CHAR(8) NULL,
    FECHANACIMIENTO CHAR(8) NULL,
    FECHACREACION CHAR(8) NULL,
    CONSTRAINT FK_ALU_CICLO FOREIGN KEY (IDCICLO) REFERENCES CICLO(IDCICLO),
    CONSTRAINT FK_ALU_TURNO FOREIGN KEY (IDTURNO) REFERENCES TURNO(IDTURNO),
    INDEX IX_ALU_NOMBRE (NOMBRE),
    INDEX IX_ALU_ESTADO (ESTADO)
) ENGINE=InnoDB;

CREATE TABLE MENSUALIDAD (
    IDMENSUALIDAD VARCHAR(50) NOT NULL PRIMARY KEY,
    IDALUMNA VARCHAR(50) NOT NULL,
    FECHAINICIO CHAR(8) NOT NULL,
    FECHAFIN CHAR(8) NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL DEFAULT 0,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'Deuda',
    IDRENOVADA VARCHAR(50) NULL,
    NOTAS VARCHAR(500) NULL,
    FECHACREACION CHAR(8) NULL,
    CONSTRAINT FK_MEN_ALU FOREIGN KEY (IDALUMNA) REFERENCES ALUMNA(IDALUMNA) ON DELETE CASCADE,
    INDEX IX_MEN_ALU (IDALUMNA)
) ENGINE=InnoDB;

CREATE TABLE PAGO (
    IDPAGO VARCHAR(50) NOT NULL PRIMARY KEY,
    IDMENSUALIDAD VARCHAR(50) NULL,
    IDALUMNA VARCHAR(50) NOT NULL,
    FECHA CHAR(8) NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    MEDIO VARCHAR(30) NOT NULL DEFAULT 'Efectivo',
    FECHACREACION CHAR(8) NULL,
    CONSTRAINT FK_PAGO_MEN FOREIGN KEY (IDMENSUALIDAD) REFERENCES MENSUALIDAD(IDMENSUALIDAD) ON DELETE SET NULL,
    CONSTRAINT FK_PAGO_ALU FOREIGN KEY (IDALUMNA) REFERENCES ALUMNA(IDALUMNA) ON DELETE CASCADE,
    INDEX IX_PAGO_FECHA (FECHA)
) ENGINE=InnoDB;

CREATE TABLE ASISTENCIA (
    IDASISTENCIA VARCHAR(50) NOT NULL PRIMARY KEY,
    IDALUMNA VARCHAR(50) NOT NULL,
    FECHA CHAR(8) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'Presente',
    FECHACREACION CHAR(8) NULL,
    CONSTRAINT UQ_ASIS_ALU_FECHA UNIQUE (IDALUMNA, FECHA),
    CONSTRAINT FK_ASIS_ALU FOREIGN KEY (IDALUMNA) REFERENCES ALUMNA(IDALUMNA) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE VENTA (
    IDVENTA VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    PRODUCTO VARCHAR(60) NULL,
    IDTURNO VARCHAR(50) NOT NULL,
    TALLA VARCHAR(5) NULL,
    OBSERVACION VARCHAR(500) NULL,
    PRECIO DECIMAL(10,2) NOT NULL DEFAULT 0,
    MEDIO VARCHAR(30) NOT NULL DEFAULT 'Efectivo',
    FECHA CHAR(8) NULL,
    CONSTRAINT FK_VENTA_TURNO FOREIGN KEY (IDTURNO) REFERENCES TURNO(IDTURNO)
) ENGINE=InnoDB;

CREATE TABLE EGRESO (
    IDEGRESO VARCHAR(50) NOT NULL PRIMARY KEY,
    FECHA CHAR(8) NOT NULL,
    CONCEPTO VARCHAR(200) NOT NULL,
    PROVEEDOR VARCHAR(200) NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    MEDIO VARCHAR(30) NOT NULL DEFAULT 'Efectivo',
    OBSERVACIONES VARCHAR(500) NULL,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE AUDITORIA (
    IDAUDITORIA VARCHAR(50) NOT NULL PRIMARY KEY,
    TABLA VARCHAR(100) NOT NULL,
    IDREGISTRO VARCHAR(50) NOT NULL,
    ACCION VARCHAR(20) NOT NULL,
    IDUSUARIO VARCHAR(50) NULL,
    FECHA CHAR(8) NOT NULL,
    HORA CHAR(8) NOT NULL,
    DETALLE VARCHAR(500) NULL
) ENGINE=InnoDB;
