USE `VoleyDB`;

-- Cambios de esquema de los requerimientos 2.12 a 2.23.
-- Se puede ejecutar sobre una base con datos: no borra nada y repetirlo no tiene efecto.

ALTER TABLE MENSUALIDAD
    ADD COLUMN IF NOT EXISTS MONTOREGULAR DECIMAL(10,2) NULL AFTER MONTO,
    ADD COLUMN IF NOT EXISTS IDPROMOCION VARCHAR(50) NULL AFTER IDRENOVADA;

ALTER TABLE VENTA
    ADD COLUMN IF NOT EXISTS IDALUMNA VARCHAR(50) NULL AFTER NOMBRE,
    ADD COLUMN IF NOT EXISTS ACUENTA DECIMAL(10,2) NULL AFTER PRECIO;

ALTER TABLE AUDITORIA
    ADD COLUMN IF NOT EXISTS IDALUMNA VARCHAR(50) NULL AFTER IDREGISTRO;

CREATE INDEX IF NOT EXISTS IX_AUD_REG ON AUDITORIA (TABLA, IDREGISTRO);
CREATE INDEX IF NOT EXISTS IX_AUD_ALU ON AUDITORIA (IDALUMNA);
CREATE INDEX IF NOT EXISTS IX_VENTA_ALU ON VENTA (IDALUMNA);
CREATE INDEX IF NOT EXISTS IX_PAGO_MEN ON PAGO (IDMENSUALIDAD);

CREATE TABLE IF NOT EXISTS PROMOCION (
    IDPROMOCION VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    TIPO VARCHAR(30) NOT NULL DEFAULT 'General',
    MONTOREGULAR DECIMAL(10,2) NOT NULL DEFAULT 0,
    MONTOPROMOCIONAL DECIMAL(10,2) NOT NULL DEFAULT 0,
    MESESPROMOCION INT NOT NULL DEFAULT 1,
    MONTOSIGUIENTES DECIMAL(10,2) NULL,
    FECHAINICIO CHAR(8) NULL,
    FECHAFIN CHAR(8) NULL,
    CONDICIONES VARCHAR(500) NULL,
    ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO_FUNCION (
    IDUSUARIO VARCHAR(50) NOT NULL,
    CODIGO VARCHAR(40) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    PRIMARY KEY (IDUSUARIO, CODIGO),
    CONSTRAINT FK_UFUN_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

UPDATE VENTA v
   SET IDALUMNA = (
       SELECT a.IDALUMNA FROM ALUMNA a
       WHERE a.NOMBRE = v.NOMBRE
       ORDER BY a.ESTADO = 'Activa' DESC, a.IDALUMNA
       LIMIT 1
   )
 WHERE v.IDALUMNA IS NULL;

INSERT IGNORE INTO SUBMODULO (IDSUBMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO, IDMODULO) VALUES
('SUB012', 'Cumpleaños', 'Cumpleañeras del día, la semana y el mes', 'faCakeCandles', 6, 1, 'MOD002'),
('SUB013', 'Deudas y vencimientos', 'Mensualidades vencidas y saldos por cobrar', 'faTriangleExclamation', 7, 1, 'MOD002'),
('SUB014', 'Reportes', 'Reportes administrativos', 'faChartColumn', 8, 1, 'MOD002'),
('SUB015', 'Promociones', 'Tarifas y promociones', 'faTags', 7, 1, 'MOD003');

DROP FUNCTION IF EXISTS fn_fecha_vista;
DROP FUNCTION IF EXISTS fn_traza;
DROP FUNCTION IF EXISTS fn_monto_promocion;

DELIMITER $$

CREATE FUNCTION fn_fecha_vista(p_Fecha CHAR(8)) RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
    IF p_Fecha IS NULL OR CHAR_LENGTH(p_Fecha) <> 8 THEN
        RETURN '';
    END IF;
    RETURN CONCAT(SUBSTRING(p_Fecha, 1, 2), '/', SUBSTRING(p_Fecha, 3, 2), '/', SUBSTRING(p_Fecha, 5, 4));
END$$

-- p_Modo 'R': quién registró (primera acción); 'M': quién hizo la última modificación.
CREATE FUNCTION fn_traza(p_Tabla VARCHAR(100), p_Id VARCHAR(50), p_Modo CHAR(1)) RETURNS VARCHAR(120)
READS SQL DATA
BEGIN
    DECLARE v_texto VARCHAR(120) DEFAULT NULL;
    IF p_Modo = 'R' THEN
        SELECT CONCAT(IFNULL(IDUSUARIO, 'sin usuario'), ' – ', fn_fecha_vista(FECHA), ' ', LEFT(HORA, 5))
          INTO v_texto
          FROM AUDITORIA
         WHERE TABLA = p_Tabla AND IDREGISTRO = p_Id AND ACCION IN ('Registrado', 'Matrícula', 'Emitido')
         ORDER BY IDAUDITORIA
         LIMIT 1;
    ELSE
        SELECT CONCAT(IFNULL(IDUSUARIO, 'sin usuario'), ' – ', fn_fecha_vista(FECHA), ' ', LEFT(HORA, 5))
          INTO v_texto
          FROM AUDITORIA
         WHERE TABLA = p_Tabla AND IDREGISTRO = p_Id AND ACCION = 'Modificado'
         ORDER BY IDAUDITORIA DESC
         LIMIT 1;
    END IF;
    RETURN v_texto;
END$$

-- Monto que corresponde al siguiente periodo de una alumna con promoción:
-- los primeros MESESPROMOCION periodos pagan MONTOPROMOCIONAL y luego MONTOSIGUIENTES.
CREATE FUNCTION fn_monto_promocion(p_IdAlumna VARCHAR(50), p_IdPromocion VARCHAR(50), p_Excluir VARCHAR(50))
RETURNS DECIMAL(10,2)
READS SQL DATA
BEGIN
    DECLARE v_usados INT DEFAULT 0;
    DECLARE v_meses INT DEFAULT 1;
    DECLARE v_promo DECIMAL(10,2);
    DECLARE v_siguientes DECIMAL(10,2);
    DECLARE v_regular DECIMAL(10,2);
    SELECT MESESPROMOCION, MONTOPROMOCIONAL, MONTOSIGUIENTES, MONTOREGULAR
      INTO v_meses, v_promo, v_siguientes, v_regular
      FROM PROMOCION WHERE IDPROMOCION = p_IdPromocion;
    SELECT COUNT(*) INTO v_usados
      FROM MENSUALIDAD
     WHERE IDALUMNA = p_IdAlumna AND IDPROMOCION = p_IdPromocion
       AND ESTADO <> 'Inactivo'
       AND (p_Excluir IS NULL OR IDMENSUALIDAD <> p_Excluir);
    IF v_usados < IFNULL(v_meses, 1) THEN
        RETURN v_promo;
    END IF;
    RETURN IFNULL(v_siguientes, v_regular);
END$$

DELIMITER ;
