USE `VoleyDB`;

-- Cambios de esquema de los requerimientos 2.12 a 2.23.
-- Se puede ejecutar sobre una base con datos: no borra nada y repetirlo no tiene efecto.

-- MySQL no admite ADD COLUMN IF NOT EXISTS ni CREATE INDEX IF NOT EXISTS.
DROP PROCEDURE IF EXISTS usp_tmp_columna;
DROP PROCEDURE IF EXISTS usp_tmp_indice;

DELIMITER $$

CREATE PROCEDURE usp_tmp_columna(IN p_Tabla VARCHAR(64), IN p_Columna VARCHAR(64), IN p_Definicion VARCHAR(300))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS
                   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_Tabla AND COLUMN_NAME = p_Columna) THEN
        SET @sql_tmp = CONCAT('ALTER TABLE ', p_Tabla, ' ADD COLUMN ', p_Columna, ' ', p_Definicion);
        PREPARE st FROM @sql_tmp;
        EXECUTE st;
        DEALLOCATE PREPARE st;
    END IF;
END$$

CREATE PROCEDURE usp_tmp_indice(IN p_Tabla VARCHAR(64), IN p_Indice VARCHAR(64), IN p_Columnas VARCHAR(200))
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.STATISTICS
                   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = p_Tabla AND INDEX_NAME = p_Indice) THEN
        SET @sql_tmp = CONCAT('CREATE INDEX ', p_Indice, ' ON ', p_Tabla, ' (', p_Columnas, ')');
        PREPARE st FROM @sql_tmp;
        EXECUTE st;
        DEALLOCATE PREPARE st;
    END IF;
END$$

DELIMITER ;

-- Columnas de VENTA que 01_esquema.sql ya trae en una instalación nueva.
ALTER TABLE VENTA MODIFY PRODUCTO VARCHAR(500) NULL;
CALL usp_tmp_columna('VENTA', 'TIPO', 'VARCHAR(30) NOT NULL DEFAULT ''Producto físico'' AFTER PRODUCTO');
CALL usp_tmp_columna('VENTA', 'COMPROBANTE', 'VARCHAR(30) NULL AFTER TIPO');
CALL usp_tmp_columna('VENTA', 'ESTADO_RECIBO', 'VARCHAR(20) NOT NULL DEFAULT ''Emitido'' AFTER FECHA');
CALL usp_tmp_columna('VENTA', 'USUARIO_EMISION', 'VARCHAR(50) NULL AFTER ESTADO_RECIBO');
CALL usp_tmp_columna('VENTA', 'FECHA_EMISION', 'CHAR(8) NULL AFTER USUARIO_EMISION');
CALL usp_tmp_columna('VENTA', 'HORA_EMISION', 'CHAR(8) NULL AFTER FECHA_EMISION');
CALL usp_tmp_columna('VENTA', 'USUARIO_MODIFICACION', 'VARCHAR(50) NULL AFTER HORA_EMISION');
CALL usp_tmp_columna('VENTA', 'FECHA_MODIFICACION', 'CHAR(8) NULL AFTER USUARIO_MODIFICACION');
CALL usp_tmp_columna('VENTA', 'HORA_MODIFICACION', 'CHAR(8) NULL AFTER FECHA_MODIFICACION');
CALL usp_tmp_columna('VENTA', 'USUARIO_ANULACION', 'VARCHAR(50) NULL AFTER HORA_MODIFICACION');
CALL usp_tmp_columna('VENTA', 'FECHA_ANULACION', 'CHAR(8) NULL AFTER USUARIO_ANULACION');
CALL usp_tmp_columna('VENTA', 'HORA_ANULACION', 'CHAR(8) NULL AFTER FECHA_ANULACION');
CALL usp_tmp_columna('VENTA', 'USUARIO_ELIMINACION', 'VARCHAR(50) NULL AFTER HORA_ANULACION');
CALL usp_tmp_columna('VENTA', 'FECHA_ELIMINACION', 'CHAR(8) NULL AFTER USUARIO_ELIMINACION');
CALL usp_tmp_columna('VENTA', 'HORA_ELIMINACION', 'CHAR(8) NULL AFTER FECHA_ELIMINACION');

CREATE TABLE IF NOT EXISTS VENTA_DETALLE (
    IDDETALLE VARCHAR(50) NOT NULL PRIMARY KEY,
    IDVENTA VARCHAR(50) NOT NULL,
    ORDEN INT NOT NULL DEFAULT 1,
    PRODUCTO VARCHAR(150) NOT NULL,
    TALLA VARCHAR(5) NULL,
    PRECIO DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_VDET_VENTA FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Las ventas anteriores al detalle quedan con una sola línea.
INSERT INTO VENTA_DETALLE (IDDETALLE, IDVENTA, ORDEN, PRODUCTO, TALLA, PRECIO)
SELECT CONCAT('DET', LPAD(b.BASE + ROW_NUMBER() OVER (ORDER BY v.IDVENTA), 6, '0')),
       v.IDVENTA, 1, LEFT(v.PRODUCTO, 150), v.TALLA, v.PRECIO
FROM VENTA v
CROSS JOIN (SELECT IFNULL(MAX(CAST(SUBSTRING(IDDETALLE, 4) AS UNSIGNED)), 0) AS BASE FROM VENTA_DETALLE) b
WHERE IFNULL(TRIM(v.PRODUCTO), '') <> ''
  AND NOT EXISTS (SELECT 1 FROM VENTA_DETALLE d WHERE d.IDVENTA = v.IDVENTA);

CALL usp_tmp_columna('MENSUALIDAD', 'MONTOREGULAR', 'DECIMAL(10,2) NULL AFTER MONTO');
CALL usp_tmp_columna('MENSUALIDAD', 'IDPROMOCION', 'VARCHAR(50) NULL AFTER IDRENOVADA');
CALL usp_tmp_columna('VENTA', 'IDALUMNA', 'VARCHAR(50) NULL AFTER NOMBRE');
CALL usp_tmp_columna('VENTA', 'ACUENTA', 'DECIMAL(10,2) NULL AFTER PRECIO');
CALL usp_tmp_columna('AUDITORIA', 'IDALUMNA', 'VARCHAR(50) NULL AFTER IDREGISTRO');
-- Días que asiste la alumna. NULL: todos los días de su turno.
CALL usp_tmp_columna('ALUMNA', 'DIASASISTENCIA', 'VARCHAR(120) NULL AFTER IDTURNO');

CALL usp_tmp_indice('AUDITORIA', 'IX_AUD_REG', 'TABLA, IDREGISTRO');
CALL usp_tmp_indice('AUDITORIA', 'IX_AUD_ALU', 'IDALUMNA');
CALL usp_tmp_indice('VENTA', 'IX_VENTA_ALU', 'IDALUMNA');
CALL usp_tmp_indice('PAGO', 'IX_PAGO_MEN', 'IDMENSUALIDAD');

DROP PROCEDURE IF EXISTS usp_tmp_columna;
DROP PROCEDURE IF EXISTS usp_tmp_indice;

CREATE TABLE IF NOT EXISTS PROMOCION (
    IDPROMOCION VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(120) NOT NULL,
    TIPO VARCHAR(30) NOT NULL DEFAULT 'General',
    MONTOREGULAR DECIMAL(10,2) NOT NULL DEFAULT 0,
    MONTOPROMOCIONAL DECIMAL(10,2) NOT NULL DEFAULT 0,
    MESESPROMOCION INT NOT NULL DEFAULT 1,
    MONTOSIGUIENTES DECIMAL(10,2) NULL,
    FECHAINICIO CHAR(8) NULL,
    FECHAFIN CHAR(8) NULL,
    CONDICIONES VARCHAR(500) NULL,
    ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
    FECHACREACION CHAR(8) NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO_FUNCION (
    IDUSUARIO VARCHAR(50) NOT NULL,
    CODIGO VARCHAR(40) NOT NULL,
    FECHAREGISTRO CHAR(8) NULL,
    PRIMARY KEY (IDUSUARIO, CODIGO),
    CONSTRAINT FK_UFUN_USU FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

UPDATE VENTA v
   SET IDALUMNA = (
       SELECT a.IDALUMNA FROM ALUMNA a
       WHERE a.NOMBRE = v.NOMBRE
       ORDER BY a.ESTADO = 'Activa' DESC, a.IDALUMNA
       LIMIT 1
   )
 WHERE v.IDALUMNA IS NULL;

INSERT IGNORE INTO SUBMODULO (IDSUBMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO, IDMODULO) VALUES
('SUB012', 'Cumpleaños', 'Cumpleañeras del día, la semana y el mes', 'faCakeCandles', 6, 1, 'MOD002'),
('SUB013', 'Deudas y vencimientos', 'Mensualidades vencidas y saldos por cobrar', 'faTriangleExclamation', 7, 1, 'MOD002'),
('SUB014', 'Reportes', 'Reportes administrativos', 'faChartColumn', 8, 1, 'MOD002'),
('SUB015', 'Promociones', 'Tarifas y promociones', 'faTags', 7, 1, 'MOD003');

DROP FUNCTION IF EXISTS fn_fecha_vista;
DROP FUNCTION IF EXISTS fn_traza;
DROP FUNCTION IF EXISTS fn_monto_promocion;

DELIMITER $$

CREATE FUNCTION fn_fecha_vista(p_Fecha CHAR(8)) RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
    IF p_Fecha IS NULL OR CHAR_LENGTH(p_Fecha) <> 8 THEN
        RETURN '';
    END IF;
    RETURN CONCAT(SUBSTRING(p_Fecha, 1, 2), '/', SUBSTRING(p_Fecha, 3, 2), '/', SUBSTRING(p_Fecha, 5, 4));
END$$

-- p_Modo 'R': quién registró (primera acción); 'M': quién hizo la última modificación.
CREATE FUNCTION fn_traza(p_Tabla VARCHAR(100), p_Id VARCHAR(50), p_Modo CHAR(1)) RETURNS VARCHAR(120)
READS SQL DATA
BEGIN
    DECLARE v_texto VARCHAR(120) DEFAULT NULL;
    IF p_Modo = 'R' THEN
        SELECT CONCAT(IFNULL(IDUSUARIO, 'sin usuario'), ' – ', fn_fecha_vista(FECHA), ' ', LEFT(HORA, 5))
          INTO v_texto
          FROM AUDITORIA
         WHERE TABLA = p_Tabla AND IDREGISTRO = p_Id AND ACCION IN ('Registrado', 'Matrícula', 'Emitido')
         ORDER BY IDAUDITORIA
         LIMIT 1;
    ELSE
        SELECT CONCAT(IFNULL(IDUSUARIO, 'sin usuario'), ' – ', fn_fecha_vista(FECHA), ' ', LEFT(HORA, 5))
          INTO v_texto
          FROM AUDITORIA
         WHERE TABLA = p_Tabla AND IDREGISTRO = p_Id AND ACCION = 'Modificado'
         ORDER BY IDAUDITORIA DESC
         LIMIT 1;
    END IF;
    RETURN v_texto;
END$$

-- Monto que corresponde al siguiente periodo de una alumna con promoción:
-- los primeros MESESPROMOCION periodos pagan MONTOPROMOCIONAL y luego MONTOSIGUIENTES.
CREATE FUNCTION fn_monto_promocion(p_IdAlumna VARCHAR(50), p_IdPromocion VARCHAR(50), p_Excluir VARCHAR(50))
RETURNS DECIMAL(10,2)
READS SQL DATA
BEGIN
    DECLARE v_usados INT DEFAULT 0;
    DECLARE v_meses INT DEFAULT 1;
    DECLARE v_promo DECIMAL(10,2);
    DECLARE v_siguientes DECIMAL(10,2);
    DECLARE v_regular DECIMAL(10,2);
    SELECT MESESPROMOCION, MONTOPROMOCIONAL, MONTOSIGUIENTES, MONTOREGULAR
      INTO v_meses, v_promo, v_siguientes, v_regular
      FROM PROMOCION WHERE IDPROMOCION = p_IdPromocion;
    SELECT COUNT(*) INTO v_usados
      FROM MENSUALIDAD
     WHERE IDALUMNA = p_IdAlumna AND IDPROMOCION = p_IdPromocion
       AND ESTADO <> 'Inactivo'
       AND (p_Excluir IS NULL OR IDMENSUALIDAD <> p_Excluir);
    IF v_usados < IFNULL(v_meses, 1) THEN
        RETURN v_promo;
    END IF;
    RETURN IFNULL(v_siguientes, v_regular);
END$$

DELIMITER ;
